apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: production-ing
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: local-2-test-dev.d.k5d.io
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: production-svc
                port:
                  number: 80
