apiVersion: v1
kind: Service
metadata:
  name: production-svc
  labels:
    app: production
    custom: happy
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: production
