apiVersion: batch/v1
kind: Job
metadata:
  name: before
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: sync-pre-job
        image: curlimages/curl
        command:
        - curl
        - "-X"
        - POST
        - "-H"
        - "Content-Type: application/json"
        - "-d"
        - '{"Result": "Pre"}'
        - "http://localhost:8080/8ecf5c9b-0dcc-471c-953d-30dcb83762a2/sync/hook"
      restartPolicy: Never
  backoffLimit: 0
