apiVersion: batch/v1
kind: Job
metadata:
  generateName: sync-success-job
  annotations:
    argocd.argoproj.io/hook: SyncFail
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
        - name: syncfail-job
          image: curlimages/curl
          command:
            - "curl"
            - "-X"
            - "POST"
            - "-H"
            - "Content-Type: application/json"
            - "-d"
            - '{"Result": "Success"}'
            - "<http://echo-server:8080/echo>"
      restartPolicy: Never
  backoffLimit: 2
